
name: "Discord Suggestion"
description: "Suggest improvements for the Discord server."
title: "[Discord Suggestion] <short summary>"
labels:
  - "Type: Suggestion"
  - "Area: Discord"
  - "Status: Needs Triage"

body:
  - type: markdown
    attributes:
      value: "## Discord Suggestion"

  - type: dropdown
    id: suggestion_type
    attributes:
      label: Suggestion Type
      options:
        - "Channel"
        - "Layout"
        - "Supporter Benefit"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
    validations:
      required: true
