name: "Mod Issue"
description: "Report a problem with a specific mod."
title: "[Mod Issue] <mod name> - <short summary>"
labels:
  - "Type: Bug"
  - "Area: Mod"
  - "Status: Needs Triage"

body:
  - type: markdown
    attributes:
      value: "## Mod Issue Report"

  - type: dropdown
    id: project_label
    attributes:
      label: Mod
      options:
        - Project: Forge Frontier Core
        - Project: Create Bigger Storage
        - Project: Dreams and Desires
        - Project: Resource Vents
    validations:
      required: true

  - type: dropdown
    id: subtype_label
    attributes:
      label: Issue Subtype
      options:
        - Texture
        - Recipe
        - Crash
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
