name: "Mod Suggestion"
description: "Suggest changes or additions to a specific mod."
title: "[Mod Suggestion] <mod name> - <short summary>"
labels:
  - "Type: Suggestion"
  - "Area: Mod"
  - "Status: Needs Triage"

body:
  - type: markdown
    attributes:
      value: "## Mod Suggestion"

  - type: dropdown
    id: project_label
    attributes:
      label: Mod
      options:
        - Project: Forge Frontier Core
        - Project: Create Bigger Storage
        - Project: Dreams and Desires
        - Project: Resource Vents
    validations:
      required: true

  - type: dropdown
    id: suggestion_type
    attributes:
      label: Suggestion Type
      options:
        - Texture
        - Recipe
        - Feature
        - Other
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
    validations:
      required: true
