
name: "Modpack Issue"
description: "Report a problem with a modpack."
title: "[Modpack Issue] <short summary>"
labels:
  - "Type: Bug"
  - "Area: Modpack"
  - "Status: Needs Triage"

body:
  - type: markdown
    attributes:
      value: "## Modpack Issue Report"

  - type: dropdown
    id: project_label
    attributes:
      label: Project
      options:
        - "Project: Create - Forge Frontier"
        - "Project: Create - Industrial Skies"
        - "Project: Landscapes Reimagined - Genesis"
    validations:
      required: true

  - type: dropdown
    id: subtype_label
    attributes:
      label: Issue Subtype
      options:
        - "Texture"
        - "Recipe"
        - "Crash"
        - "Quest"
        - "Other"
    validations:
      required: true

  - type: input
    id: modpack_version
    attributes:
      label: Modpack Version
      placeholder: "e.g. 2.5.3"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
