name: "Modpack Suggestion"
description: "Suggest improvements for a modpack."
title: "[Modpack Suggestion] <short summary>"
labels:
  - "Type: Suggestion"
  - "Area: Modpack"
  - "Status: Needs Triage"
body:
  - type: markdown
    attributes:
      value: "## Modpack Suggestion"
  - type: dropdown
    id: project_label
    attributes:
      label: Project
      options:
        - "Project: Create - Forge Frontier"
        - "Project: Create - Industrial Skies"
        - "Project: Landscapes Reimagined - Genesis"
    validations:
      required: true
  - type: dropdown
    id: suggestion_type
    attributes:
      label: Suggestion Type
      options:
        - "Texture"
        - "Recipe"
        - "Feature"
        - "Quest"
        - "Mod"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
