name: "Modpack Suggestion"
description: "Suggest changes or additions to the modpack."
title: "[Modpack Suggestion] <short summary>"
labels: ["type:suggestion", "area:modpack", "project:Modpacks", "status:needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Modpack Suggestion
        Share your idea and explain how it improves the overall experience.

  - type: dropdown
    id: modpack_name
    attributes:
      label: Which modpack?
      options:
        - Create - Forge Frontier
        - Create - Industrial Skies
        - Landscapes Reimagined - Genesis
    validations:
      required: true

  - type: dropdown
    id: modpack_suggestion_type
    attributes:
      label: Suggestion type
      options:
        - Texture suggestion
        - Recipe suggestion
        - Feature suggestion
        - Quest suggestion
    validations:
      required: true

  - type: textarea
    id: suggestion_details
    attributes:
      label: Suggestion details
      description: "Describe your idea and why it should be added."
      placeholder: "What should change or be added? Why is it beneficial?"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: "Links, examples, reference packs, or extra notes."
      render: text

  - type: markdown
    attributes:
      value: |
        ---
        Thanks for helping shape the future of the pack! 🚀
